### Подключаем пакет

In [1]:
import numpy as np
import pandas as pd
from IPython.display import display

pd.__version__

'2.3.3'

## Данные типа Series
### Основы

In [2]:
np.array([4,7,-5,3])

array([ 4,  7, -5,  3])

In [3]:
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.values

array([ 4,  7, -5,  3])

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
obj2 = pd.Series([4,7,-5,3], index=['d','b','a','c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [7]:
obj2['a']

-5

In [8]:
obj2['d'] = 6
obj2[['c','a','d']]

c    3
a   -5
d    6
dtype: int64

In [9]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [10]:
obj2*2

d    12
b    14
a   -10
c     6
dtype: int64

In [11]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [12]:
'b' in obj2

True

In [13]:
'e' in obj2

False

### Собирам Series из словаря

In [14]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [15]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [16]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj3.index = states
obj3

California    35000
Ohio          71000
Oregon        16000
Texas          5000
dtype: int64

### Наличие данных

In [17]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [18]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [19]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

### Добавление индексов

In [20]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [21]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

## Данные типа DataFrame
### Основы

In [24]:
data = {
    'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
    'year': [2000, 2001, 2002, 2001, 2002, 2003],
    'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
}
frame = pd.DataFrame(data)
# разные варианты вывода 
display(frame)
# разные варианты вывода 
print(frame)
# разные варианты вывода 
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [25]:
display(frame.head(3))
frame.tail(1)

  state  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.7
2  Ohio  2002  3.6

    state  year  pop
5  Nevada  2003  3.2

In [26]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

### Работа с адресами

In [27]:
frame2 = pd.DataFrame(
    data, 
    columns = ['иван', 'state','pop', 'debt'],
    index = ['one', 'two', 'three', 'four', 'five','six'])
frame2

      иван   state  pop debt
one    NaN    Ohio  1.5  NaN
two    NaN    Ohio  1.7  NaN
three  NaN    Ohio  3.6  NaN
four   NaN  Nevada  2.4  NaN
five   NaN  Nevada  2.9  NaN
six    NaN  Nevada  3.2  NaN

In [28]:
frame2.columns

Index(['иван', 'state', 'pop', 'debt'], dtype='object')

In [29]:
frame2['иван']

one      NaN
two      NaN
three    NaN
four     NaN
five     NaN
six      NaN
Name: иван, dtype: object

In [30]:
frame2.иван

one      NaN
two      NaN
three    NaN
four     NaN
five     NaN
six      NaN
Name: иван, dtype: object

In [31]:
display(frame2)
frame2.loc['three']

      иван   state  pop debt
one    NaN    Ohio  1.5  NaN
two    NaN    Ohio  1.7  NaN
three  NaN    Ohio  3.6  NaN
four   NaN  Nevada  2.4  NaN
five   NaN  Nevada  2.9  NaN
six    NaN  Nevada  3.2  NaN

иван      NaN
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [32]:
frame2.iloc[2]

иван      NaN
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

### Модификация данных в DataFrame

In [33]:
frame2 = pd.DataFrame(
    data, 
    columns = ['year', 'state','pop', 'debt'],
    index = ['one', 'two', 'three', 'four', 'five','six'])
frame2

frame2.debt = 16.5
frame2

       year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [34]:
frame2['debt'] = np.arange(6.)
frame2

       year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

### Вставка Series в DataFrame

In [35]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
display(val)
frame2['debt'] = val
frame2

two    -1.2
four   -1.5
five   -1.7
dtype: float64

       year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

### Поиск соответствий

In [36]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

       year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [37]:
frame2['more']  = frame2['pop']>2
frame2

       year   state  pop  debt  eastern   more
one    2000    Ohio  1.5   NaN     True  False
two    2001    Ohio  1.7  -1.2     True  False
three  2002    Ohio  3.6   NaN     True   True
four   2001  Nevada  2.4  -1.5    False   True
five   2002  Nevada  2.9  -1.7    False   True
six    2003  Nevada  3.2   NaN    False   True

In [38]:
frame2.eastern

one       True
two       True
three     True
four     False
five     False
six      False
Name: eastern, dtype: bool

In [39]:
# устаревший подход, но иногда встречается, так делать не нужно для этого есть drop
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt', 'more'], dtype='object')

In [40]:
frame2.eastern

AttributeError: 'DataFrame' object has no attribute 'eastern'

### Срезы данных

In [43]:
pop = {
    'Nevada': {2001: 2.4, 2002: 2.9},
    'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}
}
frame3 = pd.DataFrame(pop)
frame3

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [44]:
frame3.T

        2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [45]:
pd.DataFrame(pop, index=pd.Series([2001, 2002, 2003]))

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [46]:
pdata = {
    'Ohio': frame3['Ohio'][:-1],
    'Nevada': frame3['Nevada'][:2]
}
pd.DataFrame(pdata)

      Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [47]:
frame3.index.name = 'year'
frame3.columns.name = 'state'
display(frame3)
print(frame3)

state  Nevada  Ohio
year
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

state  Nevada  Ohio
year
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [48]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [49]:
frame2.values

array([[2000, 'Ohio', 1.5, nan, False],
       [2001, 'Ohio', 1.7, -1.2, False],
       [2002, 'Ohio', 3.6, nan, True],
       [2001, 'Nevada', 2.4, -1.5, True],
       [2002, 'Nevada', 2.9, -1.7, True],
       [2003, 'Nevada', 3.2, nan, True]], dtype=object)

### Индексы

In [50]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [51]:
index[1:]

Index(['b', 'c'], dtype='object')

In [52]:
labels = pd.Index(np.arange(3))
labels

Index([0, 1, 2], dtype='int64')

In [53]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [54]:
frame3

state  Nevada  Ohio
year
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [55]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [56]:
'Ohio' in frame3.columns

True

In [57]:
2003 in frame3.index

False

### Переиндексация

In [58]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [59]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [60]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [61]:
obj3.reindex(range(6))

0      blue
1       NaN
2    purple
3       NaN
4    yellow
5       NaN
dtype: object

In [62]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [63]:
obj3.reindex(range(6), method='bfill')

0      blue
1    purple
2    purple
3    yellow
4    yellow
5       NaN
dtype: object

In [64]:
frame = pd.DataFrame(
    np.arange(9).reshape((3, 3)),
    index=['a', 'c', 'd'],
    columns=['Ohio', 'Texas', 'California'])
frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [65]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [66]:
states = ['Texas', 'Utah', 'California']
fr=frame.reindex(columns=states)
fr['Utah']=[1,2,3]
fr

   Texas  Utah  California
a      1     1           2
c      4     2           5
d      7     3           8

In [67]:
frame.reindex(['a', 'b', 'c', 'd'])

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [68]:
frame.reindex(index=['a', 'b', 'c', 'd'], columns=states)

   Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

### Удаление элементов по осям Series

In [69]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [70]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [71]:
obj2 = obj.drop(['d', 'c'])

In [72]:
obj2['b']=1000
obj2

a       0.0
b    1000.0
e       4.0
dtype: float64

### Удаление элементов по осям DataFrame

In [73]:
data = pd.DataFrame(
    np.arange(16).reshape((4, 4)),
    index=['Ohio', 'Colorado', 'Utah', 'New York'],
    columns=['one', 'two', 'three', 'four'])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [74]:
data.drop(index=['Colorado', 'Ohio'])

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [75]:
data.drop(columns = ['two'])

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [76]:
data.drop(['two', 'four'], axis='columns')

          one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [77]:
data.drop(['two', 'four'], axis=1)

          one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

### Внимание! Метод Inplace (перезапись поверх)

In [78]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [79]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj.drop('c', inplace=True) # obj = obj.drop('c')
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [80]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj = obj.drop('c')
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

### Работа с индексами Series

ВНИМАНИЕ!!! здесь индексы без адресов. Особенность адресации ниже.

In [81]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [82]:
obj['b']

1.0

In [83]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [84]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [85]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [86]:
obj['b':'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [87]:
# Особенности прямой адресации
obj.iloc[0]

0.0

In [88]:
obj.iloc[1:2]

b    5.0
dtype: float64

In [89]:
obj.iloc[1:3]

b    5.0
c    5.0
dtype: float64

In [90]:
obj.loc['a']

0.0

In [91]:
obj.loc['b':'c']

b    5.0
c    5.0
dtype: float64

### Работа с индексами DataFrame

In [53]:
data = pd.DataFrame(
    np.arange(16).reshape((4, 4)),
    index=['Ohio', 'Colorado', 'Utah', 'New York'],
    columns=['one', 'two', 'three', 'four'])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [54]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [55]:
data[['three', 'one']]

          three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [56]:
data[:2]

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [57]:
display(data)
data[data['three'] > 5]

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [58]:
data < 5

            one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [59]:
data[data < 5] = 0
data

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [60]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

In [61]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [62]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [63]:
data.iloc[[1, 2], [3, 0, 1]]

          four  one  two
Colorado     7    0    5
Utah        11    8    9

In [67]:
data.iloc[:, :3][data.three > 7]

          one  two  three
Utah        8    9     10
New York   12   13     14

### Особенность индексации с целыми числами

In [96]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [99]:
# Требование использовать явную адресацию loc или iloc
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])
ser2[1]

/var/folders/lx/rgkv9ng17d76gp_n70l9pbph0000gn/T/ipykernel_3023/749700368.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ser2[1]

1.0

In [100]:
ser.iloc[:1]

0    0.0
dtype: float64

In [101]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [102]:
ser.iloc[:1]

0    0.0
dtype: float64

## Арифметика в Pandas

### считаем  с Series

In [103]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [104]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=['a', 'c', 'e', 'f', 'g'])
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [105]:
s1.add(s2)

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

### считаем  с DataFrame

In [106]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])
df1

            b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [107]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])
df2

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [108]:
df1 + df2

            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [109]:
df1 = pd.DataFrame({'A': [1, 2]})
df1

   A
0  1
1  2

In [110]:
df2 = pd.DataFrame({'B': [3, 4]})
df2

   B
0  3
1  4

In [111]:
df1 - df2

    A   B
0 NaN NaN
1 NaN NaN

In [112]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'))
df1

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [113]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list('abcde'))
df2

      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [114]:
df2.loc[1, 'b'] = np.nan
df2

      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [115]:
df1 + df2

      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [116]:
df1.add(df2, fill_value=0)

      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [117]:
1 / df1

       a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [118]:
df1.rdiv(1)

       a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [119]:
df1.reindex(columns=df2.columns, fill_value=0)

     a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

## Туда сюда, Series в DataFrame

In [120]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [121]:
arr[0]

array([0., 1., 2., 3.])

In [122]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [123]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [124]:
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [125]:
frame - series

          b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [126]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])
series2

b    0
e    1
f    2
dtype: int64

In [127]:
frame + series2

          b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [128]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [129]:
frame.sub(series3, axis='index')

          b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

## Лямбда функции

In [130]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

               b         d         e
Utah   -0.672320  0.244706 -1.133011
Ohio    0.942056 -0.471477 -0.362994
Texas   0.104297  0.617593  0.134761
Oregon  2.627155 -2.072661  0.317208

In [131]:
np.abs(frame)

               b         d         e
Utah    0.672320  0.244706  1.133011
Ohio    0.942056  0.471477  0.362994
Texas   0.104297  0.617593  0.134761
Oregon  2.627155  2.072661  0.317208

In [132]:
f = lambda x: x.max() - x.min()
frame.apply(f)

b    3.299475
d    2.690254
e    1.450218
dtype: float64

In [133]:
frame.apply( lambda x: x.max() - x.min() )

b    3.299475
d    2.690254
e    1.450218
dtype: float64

In [134]:
frame.apply( lambda x: x.max() - x.min(), axis='columns' )

Utah      1.377717
Ohio      1.413533
Texas     0.513295
Oregon    4.699816
dtype: float64

In [135]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

frame.apply(f)

            b         d         e
min -0.672320 -2.072661 -1.133011
max  2.627155  0.617593  0.317208

In [136]:
##### УСТАРЕЛО !!!

format = lambda x: '%.2f' % x
frame.applymap(format)

/var/folders/lx/rgkv9ng17d76gp_n70l9pbph0000gn/T/ipykernel_3023/3806582406.py:4: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  frame.applymap(format)

            b      d      e
Utah    -0.67   0.24  -1.13
Ohio     0.94  -0.47  -0.36
Texas    0.10   0.62   0.13
Oregon   2.63  -2.07   0.32

In [137]:
##### раньше map не работало со всем датафреймом, только поэлементно со столбцомб а теперь работает
frame.map(format)

            b      d      e
Utah    -0.67   0.24  -1.13
Ohio     0.94  -0.47  -0.36
Texas    0.10   0.62   0.13
Oregon   2.63  -2.07   0.32

In [12]:
frame['e'].map(format)

Utah       1.25
Ohio       0.12
Texas      0.61
Oregon    -0.78
Name: e, dtype: object

## Сортировка

In [13]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [14]:
frame = pd.DataFrame(np.arange(12).reshape((3, 4)),
                     index=['three', 'one', 'two'],
                     columns=['d', 'a', 'b', 'c'])
frame.sort_index()

       d  a   b   c
one    4  5   6   7
three  0  1   2   3
two    8  9  10  11

In [15]:
frame.sort_index(axis=1)

       a   b   c  d
three  1   2   3  0
one    5   6   7  4
two    9  10  11  8

In [16]:
frame.sort_index(axis=1, ascending=False)

       d   c   b  a
three  0   3   2  1
one    4   7   6  5
two    8  11  10  9

In [17]:
obj = pd.Series([4, 7, -3, 2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [18]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [19]:
frame = pd.DataFrame({'a': [0, 1, 0, 1], 'b': [4, 7, -3, 2], })
frame

   a  b
0  0  4
1  1  7
2  0 -3
3  1  2

In [20]:
frame.sort_values( by=['b'])

   a  b
2  0 -3
3  1  2
0  0  4
1  1  7

In [21]:
frame.sort_values( by=['a','b'])

   a  b
2  0 -3
0  0  4
3  1  2
1  1  7

In [22]:
frame.sort_values( by=['b','a'])

   a  b
2  0 -3
3  1  2
0  0  4
1  1  7

In [23]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [24]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [25]:
obj.rank( method='max')

0    7.0
1    1.0
2    7.0
3    5.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [26]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                      'c': [-2, 5, 8, -2.5]})
frame

     b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [27]:
frame.rank(axis='columns')

     b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [28]:
frame.rank(axis='index')

     b    a    c
0  3.0  1.5  2.0
1  4.0  3.5  3.0
2  1.0  1.5  4.0
3  2.0  3.5  1.0

## Проблема дубликата

In [29]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [30]:
obj.index.is_unique

False

In [31]:
obj['a']

a    0
a    1
dtype: int64

In [32]:
obj['c']

4

In [33]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])
df

          0         1         2
a -0.401965 -0.130680 -0.228017
a -0.730388 -0.135030 -0.873297
b -0.373391  1.198658  0.531676
b  0.029178  0.758309  0.958917

In [34]:
df.loc['b']

          0         1         2
b -0.373391  1.198658  0.531676
b  0.029178  0.758309  0.958917

### Пример, суммирование

In [35]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])
df

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [36]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [37]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [38]:
df.sum(axis=0)

one    9.25
two   -5.80
dtype: float64

In [39]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [40]:
df.describe()

            one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [41]:
df.shape

(4, 2)

## Счетчики

In [138]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'a'])
obj.unique()

array(['c', 'a', 'd', 'b'], dtype=object)

In [139]:
obj.value_counts()

a    5
c    3
b    2
d    1
Name: count, dtype: int64

In [140]:
# обратите внимание на отмену левосторонней записи в дальнейшем !!!
pd.value_counts(obj, sort=False)

/var/folders/lx/rgkv9ng17d76gp_n70l9pbph0000gn/T/ipykernel_3023/644819792.py:2: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(obj, sort=False)

c    3
a    5
d    1
b    2
Name: count, dtype: int64

In [141]:
obj.value_counts(sort=False)

c    3
a    5
d    1
b    2
Name: count, dtype: int64

## Отбор по маске

In [142]:
mask = obj.isin(['b', 'c'])
mask

0      True
1     False
2     False
3     False
4     False
5      True
6      True
7      True
8      True
9     False
10    False
dtype: bool

In [143]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [144]:
obj

0     c
1     a
2     d
3     a
4     a
5     b
6     b
7     c
8     c
9     a
10    a
dtype: object

### Дамми переменные

In [145]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                   'data1': range(6)})
display(df)
pd.get_dummies(df['key'])

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

       a      b      c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [146]:
# команда не работает в правой записи ... печально
df['key'].get_dummies(prefix='key')

AttributeError: 'Series' object has no attribute 'get_dummies'

In [147]:
dummies = pd.get_dummies(df['key'], prefix='key')
display(dummies)
df_with_dummy = df[['data1']].join(dummies)
df_with_dummy

   key_a  key_b  key_c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

   data1  key_a  key_b  key_c
0      0  False   True  False
1      1  False   True  False
2      2   True  False  False
3      3  False  False   True
4      4   True  False  False
5      5  False   True  False